version: '3.8'
services:
  frontend:
    build: ./weather-app-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_SERVER_URL=http://backend:8080

  backend:
    build: ./weather-app-backend/weather-app-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
